# Тема “Вычисления с помощью Numpy”

In [8]:
import numpy as np

#### Задание 3

Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [9]:
A = np.array([[1,6],
            [2, 8],
            [3, 11],
            [3, 10],
            [1, 7]])

In [10]:
A

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [12]:
mean_a = np.mean(A, axis = 0)

In [13]:
mean_a

array([2. , 8.4])

In [14]:
a_centered = np.subtract(A, mean_a)

In [15]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [28]:
ac_1 = a_centered[:, 0]

In [29]:
ac_1

array([-1.,  0.,  1.,  1., -1.])

In [30]:
ac_2 = a_centered[:, 1]

In [31]:
ac_2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [32]:
a_centered_sp = ac_1@ac_2

In [33]:
a_centered_sp

8.0

In [34]:
res = a_centered_sp / 4

In [35]:
res

2.0