# Тема “Вычисления с помощью Numpy”

In [1]:
import numpy as np

#### Задание 4

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь:
Выборочная ковариация и выборочная дисперсия — Студопедия
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [2]:
A = np.array([[1,6],
            [2, 8],
            [3, 11],
            [3, 10],
            [1, 7]])

In [3]:
A

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = np.mean(A, axis = 0)

In [5]:
mean_a

array([2. , 8.4])

In [6]:
a_centered = np.subtract(A, mean_a)

In [7]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [8]:
ac_1 = a_centered[:, 0]

In [9]:
ac_1

array([-1.,  0.,  1.,  1., -1.])

In [10]:
ac_2 = a_centered[:, 1]

In [11]:
ac_2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [12]:
a_centered_sp = ac_1@ac_2

In [13]:
a_centered_sp

8.0

In [14]:
res = a_centered_sp / 4

In [15]:
res

2.0

In [16]:
at = A.transpose()

In [17]:
at

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [18]:
np.cov(at)

array([[1. , 2. ],
       [2. , 4.3]])