# Тема “Вычисления с помощью Numpy”

In [1]:
import numpy as np

#### Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [2]:
A = np.array([[1,6],
            [2, 8],
            [3, 11],
            [3, 10],
            [1, 7]])

In [3]:
A

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = np.mean(A, axis = 0)

In [5]:
mean_a

array([2. , 8.4])

In [6]:
a_centered = np.subtract(A, mean_a)

In [7]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])